version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_app_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:6.2-alpine
    container_name: my-redis-cache
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  db_data:
